plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md

remote_theme: mmistakes/so-simple-theme
locale: en-US
title: ""
description: ""
date_format: "%B %-d, %Y"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# Liquid
liquid:
  error_mode: strict
  
markdown: kramdown

author: Trevin Jones
